export const BUSCAR_TODAS_TAREFAS = 'BUSCAR_TODAS_TAREFAS';
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA';
export const ALTERAR_TAREFA = 'ALTERAR_TAREFA';
export const ALTERAR_FILTRO_TAREFAS_CONCLUIDAS = 'ALTERAR_FILTRO_TAREFAS_CONCLUIDAS';

